# Generated by Django 6.0.5 on 2026-06-09 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_display_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
